import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sea Hawk Adventures',
  description: 'Generated by create next app',
  metadataBase: new URL('https://www.seahawkadventures.com/'),
  openGraph: {
    url: "https://www.seahawkadventures.com/",
    title: "My Website",
    description: "My Website Description",
    siteName: "Sea Hawk Adventures",
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
